/**
 * MSG91 OTP provider (OD-005 — resolved Phase 3.18).
 *
 * Concrete `OtpProvider` using the MSG91 legacy SendOTP API
 * (`https://api.msg91.com`):
 *
 *   - send:      GET /api/sendotp.php?authkey=&mobile=&sender=&message=&otp_expiry=&otp_length=
 *   - verify:    GET /api/verifyRequestOTP.php?authkey=&mobile=&otp=
 *   - retry:     GET /api/retryotp.php?authkey=&mobile=&retrytype=text
 *
 * The OTP is generated by MSG91 (no `otp` parameter) and must appear in the
 * message via the `##OTP##` placeholder. `mobile` is the E.164 phone WITHOUT
 * the leading `+` (MSG91 wire format).
 *
 * Contract:
 *   - `authKey` null (unconfigured) → fails closed (`ExternalServiceError`).
 *   - Transport/timeout/parse failures → `ExternalServiceError`.
 *   - `verifyOtp` maps provider `type: error` to `false` (the caller converts
 *     it to a generic 401); provider error MESSAGES are never propagated.
 *
 * `fetchFn` is injectable for deterministic tests (never the real network).
 */
import { ExternalServiceError } from '../../../lib/errors.js';
import { toProviderPhone, type E164Phone } from '../domain/phone.js';
import type { OtpProvider } from '../application/otp-provider.js';

export const MSG91_BASE_URL = 'https://api.msg91.com';
export const MSG91_DEFAULT_SENDER_ID = 'SMSIND';
export const MSG91_DEFAULT_OTP_EXPIRY_MINUTES = 5;
export const MSG91_DEFAULT_OTP_LENGTH = 6;

/** Provider request timeout. */
export const MSG91_TIMEOUT_MS = 10_000;

/** SMS body; `##OTP##` is replaced by MSG91 with the generated code. */
const MSG91_OTP_MESSAGE =
  'Your RidePool OTP is ##OTP##. Valid for ##OTP_EXPIRY## minutes.';

export interface Msg91ProviderConfig {
  /** Backend-only secret. Null → the provider fails closed. */
  authKey: string | null;
  /** 3–6 char sender id (defaults to SMSIND). */
  senderId?: string | null;
  /** Base URL (defaults to https://api.msg91.com). */
  baseUrl?: string;
  /** OTP validity in minutes (1–1440). */
  otpExpiryMinutes?: number;
  /** OTP digit count (4–9). */
  otpLength?: number;
  /** Injectable fetch (tests); defaults to globalThis.fetch. */
  fetchFn?: typeof fetch;
}

/** The MSG91 response shape we rely on. */
interface Msg91Response {
  type?: string;
  message?: string;
}

export function createMsg91OtpProvider(
  config: Msg91ProviderConfig,
): OtpProvider {
  const baseUrl = (config.baseUrl ?? MSG91_BASE_URL).replace(/\/+$/, '');
  const senderId = config.senderId ?? MSG91_DEFAULT_SENDER_ID;
  const otpExpiryMinutes =
    config.otpExpiryMinutes ?? MSG91_DEFAULT_OTP_EXPIRY_MINUTES;
  const otpLength = config.otpLength ?? MSG91_DEFAULT_OTP_LENGTH;
  const fetchFn = config.fetchFn ?? globalThis.fetch;

  async function getJson(url: URL): Promise<Msg91Response | null> {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), MSG91_TIMEOUT_MS);
    let response: Response;
    try {
      response = await fetchFn(url.toString(), { signal: controller.signal });
    } catch (err) {
      throw new ExternalServiceError('OTP service is unavailable', {
        cause: err,
      });
    } finally {
      clearTimeout(timer);
    }

    const text = await response.text();
    try {
      return JSON.parse(text) as Msg91Response | null;
    } catch {
      throw new ExternalServiceError(
        'OTP service returned an invalid response',
        {
          cause: new Error(text.slice(0, 200)),
        },
      );
    }
  }

  function endpoint(path: string, params: Record<string, string>): URL {
    const url = new URL(`${baseUrl}${path}`);
    for (const [key, value] of Object.entries(params)) {
      url.searchParams.set(key, value);
    }
    return url;
  }

  return {
    async requestOtp(phone: E164Phone): Promise<void> {
      const authKey = config.authKey;
      if (!authKey) {
        throw new ExternalServiceError('OTP service is not configured');
      }
      const url = endpoint('/api/sendotp.php', {
        authkey: authKey,
        mobile: toProviderPhone(phone),
        sender: senderId,
        message: MSG91_OTP_MESSAGE,
        otp_expiry: String(otpExpiryMinutes),
        otp_length: String(otpLength),
      });
      const body = await getJson(url);
      if (body?.type !== 'success') {
        throw new ExternalServiceError('Failed to send the OTP', {
          cause: new Error(body?.message ?? 'unknown provider response'),
        });
      }
    },

    async verifyOtp(phone: E164Phone, otp: string): Promise<boolean> {
      const authKey = config.authKey;
      if (!authKey) {
        throw new ExternalServiceError('OTP service is not configured');
      }
      const url = endpoint('/api/verifyRequestOTP.php', {
        authkey: authKey,
        mobile: toProviderPhone(phone),
        otp,
      });
      const body = await getJson(url);
      if (body?.type === 'success') {
        return true;
      }
      if (body?.type === 'error') {
        // Wrong/expired code: report rejection only — never the provider's
        // reason message, which could reveal verification internals.
        return false;
      }
      throw new ExternalServiceError(
        'OTP service returned an invalid response',
      );
    },

    async retryOtp(phone: E164Phone): Promise<void> {
      const authKey = config.authKey;
      if (!authKey) {
        throw new ExternalServiceError('OTP service is not configured');
      }
      const url = endpoint('/api/retryotp.php', {
        authkey: authKey,
        mobile: toProviderPhone(phone),
        retrytype: 'text',
      });
      const body = await getJson(url);
      if (body?.type !== 'success') {
        throw new ExternalServiceError('Failed to resend the OTP', {
          cause: new Error(body?.message ?? 'unknown provider response'),
        });
      }
    },
  };
}
